In [1]:
import pandas as pd


data = {
    "day": [f"D{i}" for i in range(1, 21)],
    "outlook": ["sunny", "sunny", "overcast", "rain", "rain", "rain", "overcast",
                "sunny", "sunny", "rain", "sunny", "overcast", "overcast", "rain",
                "sunny", "rain", "overcast", "sunny", "rain", "overcast"],
    "temperature": ["hot", "hot", "hot", "monsoon", "cold", "cold", "cold",
                     "monsoon", "cold", "monsoon", "monsoon", "monsoon", "hot", "monsoon",
                     "storm", "storm", "storm", "storm", "storm", "storm"],
    "humidity": ["high", "high", "high", "high", "normal", "normal", "normal",
                  "high", "normal", "normal", "normal", "high", "normal", "high",
                  "high", "high", "normal", "normal", "normal", "high"],
    "wind": ["weak", "strong", "weak", "weak", "weak", "strong", "strong",
             "weak", "weak", "weak", "strong", "strong", "weak", "strong",
             "strong", "strong", "weak", "weak", "strong", "weak"],
    "play_golf": ["no", "no", "yes", "yes", "yes", "no", "yes",
                   "no", "yes", "yes", "yes", "yes", "yes", "no",
                   "no", "no", "yes", "yes", "no", "yes"],
}

df = pd.DataFrame(data)
df.head()

  day   outlook temperature humidity    wind play_golf
0  D1     sunny         hot     high    weak        no
1  D2     sunny         hot     high  strong        no
2  D3  overcast         hot     high    weak       yes
3  D4      rain     monsoon     high    weak       yes
4  D5      rain        cold   normal    weak       yes

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()
df['outlook']= le.fit_transform(df['outlook'])
df['temperature']= le.fit_transform(df['temperature'])
df['humidity']= le.fit_transform(df['humidity'])
df["wind"]= le.fit_transform(df['wind'])
df["play_golf"]= le.fit_transform(df['play_golf'])

In [3]:
X = df.iloc[:,1:-1]
y = df[['play_golf']]
X

    outlook  temperature  humidity  wind
0         2            1         0     1
1         2            1         0     0
2         0            1         0     1
3         1            2         0     1
4         1            0         1     1
5         1            0         1     0
6         0            0         1     0
7         2            2         0     1
8         2            0         1     1
9         1            2         1     1
10        2            2         1     0
11        0            2         0     0
12        0            1         1     1
13        1            2         0     0
14        2            3         0     0
15        1            3         0     0
16        0            3         1     1
17        2            3         1     1
18        1            3         1     0
19        0            3         0     1

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [5]:
y

    play_golf
0           0
1           0
2           1
3           1
4           1
5           0
6           1
7           0
8           1
9           1
10          1
11          1
12          1
13          0
14          0
15          0
16          1
17          1
18          0
19          1

In [6]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0

In [ ]:
from sklearn.tree import plot_tree
plot_tree

In [ ]:
def add()